### ISSUE TITLE
Exclude routes

### ISSUE THREAD

**Issue by chiqui3d** [norberttech/static-content-generator-bundle#2]
How do I have to render all the routes, except the ones that have or start with `/admin`?

**Comment by norberttech** [comment]
Hey @chiqui3d if all those routes also has a name that starts with `admin_` prefix you could use `--filter-route-prefix=admin_` option. 
Filtering out by actual route URL is not supported yet but I might take another look into it if using route name does not work for you.

**Comment by chiqui3d** [comment]
Yes, they start with admin_, then the filter is to include or exclude?, excuse my question.

The idea is to be able to exclude, above all it will happen to more people who maybe have an internal CMS to manage the blog, but only want to upload the static part, then the ideal would be to exclude everything you want.

**Comment by norberttech** [comment]
Right, makes total sense, filter will include. Let me look into this and get back to you with a solution next week! In case you could find some time, feel free open a pull request if you find a way to make it work.
This is very good feedback, thanks

**Comment by norberttech** [comment]
https://github.com/norberttech/static-content-generator-bundle/issues/3 I believe this should do the trick
