### ISSUE TITLE
Dependency Issue in Symfony 6.1

### ISSUE THREAD

**Issue by JWBrownie** [norberttech/static-content-generator-bundle#237]
Hi,

I am working on adding this bundle to my Symfony 6.1 but it fails to install with the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires norberttech/static-content-generator-bundle ^0.4.0 -> satisfiable by norberttech/static-content-generator-bundle[0.4.0].
    - norberttech/static-content-generator-bundle 0.4.0 requires symfony/browser-kit ^4.4|^5.0 -> found symfony/browser-kit[v4.4.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but these were not loaded, likely because it conflicts with another require.
```

Is this beautiful bundle going to be compatible with Symfony 6.1 anytime soon? Please, I am not capable of fixing it myself.

For your attention thank you very much.
Regards,

**Comment by norberttech** [comment]
heey @JWBrownie could you please check the latest changes I merged today? If this will work I will publish another release
